# https://travis-ci.org/jwtk/jjwt

#sudo: required
language: java
jdk:
  - openjdk7
  - oraclejdk8
  - oraclejdk9
  - oraclejdk10
  - openjdk10
# - openjdk11
# - oraclejdk-ea

before_install:
  - export BUILD_COVERAGE="$([ $TRAVIS_JDK_VERSION == 'oraclejdk8' ] && echo 'true')"

install: true

script: mvn install

after_success:
  - test -z "$BUILD_COVERAGE" || { mvn clean clover:setup test && mvn -pl . clover:clover clover:check coveralls:report; }
